---
#-------------------------------
# General Site Settings

title: My Portfolio
logo:
author: Bhavesh Koirala
description: Computer Engineering Student Portfolio
email: bkoirala2004@gmail.com
phone: 682-359-6773
address: 3000 Northside Blvd, Apt 2-336, Richardson, TX 75080
copyright: Copyright &copy; 2023

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I'm <br> Bhavesh <br> Computer Engineering student.

social:
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/bhavesh-koirala-yes" }
  - { icon: "ti-github", link: "https://github.com/bhavesh-koirala" }

#-------------------------------
# About Section

blurb: I like designing PCB's and building it into a working device. As a computer engineering student I am passionate about working with embedded systems from the design, development and testing. I also really like video editing and outreach in general.

blurb-btn-link: "/about"
blurb-btn-name: know more

#-------------------------------
# Skills Section

skills-title: Technical Skills
skills:
  - { name: Programming (Java, C++, C, Verilog), color: "#fdb157", value: "75%" }
  - { name: PCB Design (KiCad, Altium), color: "#9473e6", value: "70%" }
  - { name: Hardware Tools (Arduino, Oscilloscopes, RF generators), color: "#bdecf6", value: "75%" }
  - { name: CAD & Simulation (SolidWorks, Matlab), color: "#ffbcaa", value: "65%" }

#-------------------------------
# Experience Section

experience-title: Activities & Experience
experience:
  - {
      name: Robotics Club - Combat Robotics & Marketing Team,
      icon: "icon-1.png",
      date: "Aug 2022 - Present",
      organization: "UTD",
    }
  - {
      name: Dallas Formula Racing - Electrical & Embedded Team,
      icon: "icon-2.png",
      date: "Aug 2023 - Present",
      organization: "UTD",
    }
  - {
      name: Wireless Drone Charging Research Helper,
      icon: "icon-3.png",
      date: "2024",
      organization: "UTD",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Bachelor of Science in Computer Engineering,
      date: "2022 - Present",
      organization: "University of Texas at Dallas",
    }
  - {
      name: High School Diploma,
      date: "2018 - 2022",
      organization: "Fossil Ridge High School",
    }

#-------------------------------
# Services Section

services-title: Areas of Expertise
services:
  - {
      name: PCB Design & Hardware Development,
      icon: ti-panel,
      description: "Experience in designing custom PCB layouts using KiCad and Altium, with focus on ESP32 and embedded systems.",
      active: true,
    }
  - {
      name: Embedded Systems Programming,
      icon: ti-settings,
      description: "Proficient in programming microcontrollers using C++ and Arduino, implementing sensors and display interfaces.",
      active: true,
    }
  - {
      name: Hardware Testing & Prototyping,
      icon: ti-pulse,
      description: "Skilled in using RF generators, oscilloscopes, multimeters, and other testing equipment for hardware development.",
      active: true,
    }

#-------------------------------
# Portfolio Section

portfolio-items:
  - image: "assets/images/portfolio/sonar.png"
    url: "#"
    portfolio-type:
      - type: "Embedded Systems"
    title: "Sonar Detector"
    description: "Developed a precision sonar detector with LCD display using Arduino and C++"
  
  - image: "assets/images/portfolio/esp32.png"
    url: "#"
    portfolio-type:
      - type: "PCB Design"
    title: "Custom ESP32 Layout"
    description: "Designed a custom ESP32 PCB with Bluetooth and Wi-Fi connectivity using KiCad"
  
  - image: "assets/images/portfolio/thermometer.png"
    url: "#"
    portfolio-type:
      - type: "Embedded Systems"
    title: "Dual Temperature Sensor"
    description: "Created a precise dual temperature sensor for room and water temperature measurement"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: bkoirala2004@gmail.com
contact-phone: 682-359-6773
contact-address: 3000 Northside Blvd, Apt 2-336, Richardson, TX 75080
